services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: backenduser
      POSTGRES_PASSWORD: 8VX8QBCZD9Guy330k
      POSTGRES_DB: website_backend
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend: